//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Jewelries_ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costumer()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> avg_grade { get; set; }
        public string password { get; set; }
        public Nullable<bool> is_manager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
