//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Jewelries_ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int product_id { get; set; }
        public int costumer_id { get; set; }
        public Nullable<double> amount { get; set; }
        public string costumer_person { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    
        public virtual Costumer Costumer { get; set; }
        public virtual Product Product { get; set; }
    }
}
